# Test Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campus_wall
    username: xiaobai
    password: 20020626Bx/

  data:
    redis:
      host: localhost
      port: 6379
      password: 20020626Bx/

  flyway:
    clean-disabled: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  level:
    com.campus.wall: info
